// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.Checks":       schema_pkg_apis_pingdom_v1alpha1_Checks(ref),
		"github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.ChecksSpec":   schema_pkg_apis_pingdom_v1alpha1_ChecksSpec(ref),
		"github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.ChecksStatus": schema_pkg_apis_pingdom_v1alpha1_ChecksStatus(ref),
	}
}

func schema_pkg_apis_pingdom_v1alpha1_Checks(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Checks is the Schema for the checks API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.ChecksSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.ChecksStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.ChecksSpec", "github.com/markelog/pingdom-operator/pkg/apis/pingdom/v1alpha1.ChecksStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_pingdom_v1alpha1_ChecksSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChecksSpec defines the desired state of Checks",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_pingdom_v1alpha1_ChecksStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChecksStatus defines the observed state of Checks",
				Type:        []string{"object"},
			},
		},
	}
}
